### ISSUE TITLE
点击页面元素没反应

### ISSUE THREAD

**Issue by ywager** [zh-lx/webpack-vue-debug#12]
mac系统下，点击页面元素没反应，且终端控制台提示如下错误：
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/17868062/167785200-9cd5a0c0-9761-407b-b6ea-4add6eff278e.png">
添加如下配置，点击跳转正常，建议在README中补充下：
<img width="710" alt="image" src="https://user-images.githubusercontent.com/17868062/167785010-414bb39d-bc3b-4701-b663-30d82d9e2b88.png">

**Comment by zh-lx** [comment]
感谢反馈，请问使用的 `webpack-vue-debug` 版本是多少呢？1.1.1 版本后我优化了下应该是不需要添加 `.env.local` 文件的

**Comment by ywager** [comment]
"webpack-vue-debug": "^1.1.1"

**Comment by zh-lx** [comment]
> Author

感谢反馈，已在 readme 中补充，另外又进一步做了优化，如果方便的话，请下载 1.1.2 版本试一下在不添加 `.env.local` 的情况下，点击页面是否会有反应，感谢！

**Comment by ywager** [comment]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/17868062/168944584-e3994b4d-b0c8-45c5-8906-c659b85ba68b.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/17868062/168944604-8fea4927-a60b-44c5-b21e-9dd8671fa0a5.png">
"webpack-vue-debug": "^1.1.2"，改成1.1.2后点击页面元素还是提示需要配置.env.local

**Comment by zh-lx** [comment]
> <img alt="image" width="1500" src="https://user-images.githubusercontent.com/17868062/168944584-e3994b4d-b0c8-45c5-8906-c659b85ba68b.png">
> 
> <img alt="image" width="495" src="https://user-images.githubusercontent.com/17868062/168944604-8fea4927-a60b-44c5-b21e-9dd8671fa0a5.png">
> 
> "webpack-vue-debug": "^1.1.2"，改成1.1.2后点击页面元素还是提示需要配置.env.local

好吧，可能是不同的 mac 电脑里面的 vscode 运行路径及名称不同，我还是在 readme 中补充一下兜底配置吧。感谢您的反馈
