### ISSUE TITLE
能否支持Hbuilder？

### ISSUE THREAD

**Issue by mzky** [zh-lx/webpack-vue-debug#8]
工具看着很不错，不知道能否支持一下Hbuilder，用这个是因为可以实时调试，保存的时候自动刷新页面
![image](https://user-images.githubusercontent.com/13345233/158285812-8fd7ddff-63e1-489e-a28f-4c4bc75066c9.png)
插件说明：
https://hx.dcloud.net.cn/ExtensionTutorial/README?id=%e5%a6%82%e4%bd%95%e5%bc%80%e5%8f%91%e4%b8%80%e4%b8%aa%e6%8f%92%e4%bb%b6%ef%bc%9f

**Comment by zh-lx** [comment]
感谢反馈！这周末我会看一下是否能支持

**Comment by zh-lx** [comment]
> 工具看着很不错，不知道能否支持一下Hbuilder，用这个是因为可以实时调试，保存的时候自动刷新页面 ![image](https://user-images.githubusercontent.com/13345233/158285812-8fd7ddff-63e1-489e-a28f-4c4bc75066c9.png) 插件说明： https://hx.dcloud.net.cn/ExtensionTutorial/README?id=%e5%a6%82%e4%bd%95%e5%bc%80%e5%8f%91%e4%b8%80%e4%b8%aa%e6%8f%92%e4%bb%b6%ef%bc%9f

已在 `1.1.0` 版本中支持了 HBuilder，请安装最新版本体验

**Comment by zh-lx** [comment]
已在 `1.1.0` 版本中支持了 HBuilder，请安装最新版本体验
